name: Deploy to GCP Bucket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Get your GitHub files
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # 3. Install gcloud + gsutil
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # 4. Upload files to bucket
      - name: Upload files to GCS
        run: |
          gsutil -m rsync -r -d ./ gs://cloudweb3
